# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'TengwarFont' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TengwarFont
  pod 'EFIconFont'

end
